### ISSUE TITLE
scope库模块无法识别

### ISSUE THREAD

**Issue by LightGlobal** [node-modules/autod#26]
不支持scope库模块命名，比如require('@xxx/moduleName')，无法识别该模块

**Comment by dead-horse** [comment]
支持的，哪个不支持？

**Comment by LightGlobal** [comment]
多谢，是支持的，只要加入-r配置就好了；  还有另外一个问题，能否不安装最新版本，尤其是主版本号，主版本号是不兼容更新，容易引入新问题，导致项目不稳定

**Comment by dead-horse** [comment]
用 --semver 参数指定 --sermver=koa@next,debug@1
