### ISSUE TITLE
what does "get remote version error" mean ?

### ISSUE THREAD

**Issue by nikogu** [node-modules/autod#29]
![image](https://user-images.githubusercontent.com/1179603/32586771-438bace8-c4ca-11e7-97be-ac7aba09e499.png)

- version: 2.10.1
- node: 8.5.0

**Comment by dead-horse** [comment]
maybe network error and can't get these packages' version from npm registry. please try again or use another mirror registry like `--registry=https://registry.npm.taobao.org`
